---  
- summary: | 
    Проверка оформления заказа. # проверка главного функционала #
  requirement: |
    Тестируемое требование: Пользователь может оформить заказ на добавленный товар в корзинуу.
  prerequisites: |
    no-data    
  test-data: |
    no-data  
  steps:
    - Добаить любой товар в "Корзину", любым способом.
    - Открыть страницу "Корзина".
    - Клик на кнопку "Оформить заказ".    
  expected-result: |
    - Заказ успешно оформлен.

- summary: |
    Проверка смены языка на русский. 
  requirement: |
    Тестируемое требование: При смене языка, все страницы магазина должна отображаться на русском языке.
  prerequisites: |
    no-data.
  test-data: |
    no-data  
  steps:
    - Клик на Выпадающий список "Language".
    - Выбрать русский язык.       
  expected-result: |    
    - Локаль сайта отображается на русском.   
