---  
- summary: | 
    Проверка обязательных полей формы регистрации.
  requirement: |
    Тестируемое требование: Все обязательные поля формы регистрации должны быть заполнены перед отправкой формы.
  prerequisites: |
    Открыта форма регистрации.
  test-data: |
    Тестовые данные:
    Nickname = Gnom123
    Email = Gnom123@gmail.com
    Password = werwersdfxcv342
    Password Confirmation = werwersdfxcv342  
  steps:
    - Вводим Nickname.
    - Вводим Email.
    - Вводим Password. 
    - Password Confirmation.
    - Нажимаем кнопку "Submit".
  expected-result: |
    - Форма заполнена успешно. Происходит переход по главную страницу сайта.

- summary: |
    Проверка регистрации без заполнения обязательных полей.        # негативный тест-кейс.
  requirement: |
    Тестируемое требование: Все обязательные поля, обязательны для заполнения, а так же наличие предупреждения, что поле не заполнено.
  prerequisites: |
    Открыта форма регистрации.
  test-data: |
    no-data  
  steps:
    - Нажимаем кнопку "Submit".           
  expected-result: |    
    - Регистрация провалена. Появились сообщения: Nickname required, Email required, Password required, Confirmation required.  
